---
title: "Template Title"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}

source(here("HingeToLength.R"))

```

# Data

```{r}

Brief_Res <- readRDS(here("data","Brief_res.rds")) %>% 
                mutate(length=hingetolength(hinge))


# Test fit
Brief_Res %>% ggplot() +
  aes(hinge, length) +
  geom_point() +
  geom_smooth() +
  coord_fixed() + ylim(0, NA) +
  geom_point(data = hinge_length,col="red",alpha=0.2)

```



# Stats

```{r}
# Extract statistical values
age_summary <- summary(Brief_Res$age)
# length_summary <- summary(Brief_Res$length)
hinge_summary <- summary(Brief_Res$hinge)

# Create a table
table_data <- data.frame(
  Variable = c("Age", "Length", "Hinge"),
  Minimum = round(c(age_summary["Min."], hingetolength(hinge_summary["Min."]), hinge_summary["Min."]), 1),
  `1st Quartile` = round(c(age_summary["1st Qu."], hingetolength(hinge_summary["1st Qu."]), hinge_summary["1st Qu."]), 1),
  Median = round(c(age_summary["Median"], hingetolength(hinge_summary["Median"]), hinge_summary["Median"]), 1),
  Mean = round(c(age_summary["Mean"], hingetolength(hinge_summary["Mean"]), hinge_summary["Mean"]), 1),
  `3rd Quartile` = round(c(age_summary["3rd Qu."], hingetolength(hinge_summary["3rd Qu."]), hinge_summary["3rd Qu."]), 1),
  Maximum = round(c(age_summary["Max."], hingetolength(hinge_summary["Max."]), hinge_summary["Max."]), 1)
)


# Convert table to markdown
markdown_table <- knitr::kable(table_data, format = "markdown")

# Print the markdown table
print(markdown_table)

```

