---
title: "Oyster harvests"
author: "Niklas Hausmann"
date: "Today"
output: pdf_document
---

# Libraries 
```{r Libraries,echo=FALSE,message = FALSE,warning = FALSE}
knitr::opts_chunk$set(echo=FALSE,message = FALSE,warning = FALSE)

{
  pacman::p_load(
    here,
    janitor,
    tidyverse,
    cowplot,ggx,lubridate,
    patchwork,
    RColorBrewer) 
  
  theme_set(theme_cowplot())
}
```

# Data

```{r}

Hist_Oy <- read.csv(here("Data","hist_oysters.csv")) %>% 
  mutate(year=round(year,0),
         oysters=round(oysters,2))

```

# Plot
```{r}

Plot_A <- Hist_Oy %>% 
  filter(year<1830) %>% 
  ggplot()+
  aes(year,oysters)+
  geom_col(fill="black",width = 0.8)+
  scale_x_continuous(breaks = c(1773,1780,1790,1800,1810),limits = c(1772,1810))+
  scale_y_continuous(breaks = c(0,0.1,0.2,0.3,0.4,0.5),limits = c(0,0.5))+
  xlab("Year")+
  ylab("Oysters in millions")

Plot_B <- Hist_Oy %>% 
  filter(year>1830) %>% 
  ggplot()+
  aes(year,oysters)+
  geom_col(fill="black",width = 0.8)+
  scale_x_continuous(breaks = c(1869,1875,1885,1895,1905,1915,1925),limits = c(1868,1925))+
  scale_y_continuous(breaks = c(0,0.5,1,2,4,6),limits = c(0,6))+
  xlab("Year")+
  ylab("")

Plot_A+Plot_B+plot_annotation(title = "Oyster harvests",subtitle = "Wadden Sea",tag_levels = "A")+plot_layout(widths = c(0.4,0.6))
```

# Save
```{r}

ggsave(filename = "Oyster_harvests.png")

```



